package com.example.autosellingapp.utils;

public class Constant {
    public static final String API_KEY = "dothanhtuan";
    public static final String TAG_ROOT = "ADS_CAR";
    public static final String SERVER_URL = "http://192.168.94.120/autobuy/api.php";
    public static final String TAG_MANU_ID = "manu_id";
    public static final String TAG_MANU_NAME = "manu_name";
    public static final String TAG_MANU_THUMB = "manu_thumb";
    public static final String METHOD_MANUFACTURER = "manufacturer_list";
    public static final String TAG_MANU = "manufacturer";
    public static final String TAG_MODEL = "model";
    public static final String TAG_CITY = "city";
    public static final String TAG_BODY_TYPE = "bodytype";
    public static final String TAG_FUEL_TYPE = "fueltype";
    public static final String TAG_MODEL_ID = "model_id";
    public static final String TAG_MODEL_NAME = "model_name";
    public static final String TAG_CITY_ID = "city_id";
    public static final String TAG_CITY_NAME = "city_name";
    public static final String TAG_BODY_TYPE_ID = "bodytype_id";
    public static final String TAG_BODY_TYPE_NAME = "bodytype_name";
    public static final String TAG_FUEL_TYPE_ID = "fueltype_id";
    public static final String TAG_FUEL_TYPE_NAME = "fueltype_name";
    public static final String METHOD_SEARCH = "search_method";
    public static final String TEXT_MANU_LIST = "Manufacturer";
    public static final String TEXT_MODEL_LIST = "Model";
    public static final String TEXT_CITY_LIST = "City";
    public static final String TEXT_BODY_TYPE_LIST = "Body type";
    public static final String TEXT_FUEL_TYPE_LIST = "Fuel type";
    public static final String TEXT_CONDITION = "Condition";
    public static final String TAG_TRANS = "transmission";
    public static final String TAG_COLOR = "color";
    public static final String TAG_TRANS_ID = "trans_id";
    public static final String TAG_TRANS_NAME = "trans_name";
    public static final String TAG_COLOR_ID = "color_id";
    public static final String TAG_COLOR_NAME = "color_name";
    public static final String TAG_COLOR_CODE = "color_code";

    public static final String TEXT_TRANS = "Transmission";
    public static final String TEXT_COLOR= "Body color";
    public static final String TEXT_YEAR = "Year";
    public static final String TEXT_SEAT = "Seat number";
    public static final String TEXT_DOOR = "Door number";
    public static final String TEXT_PREUSER = "Previous user number";
    public static final String TEXT_PRICE = "Price";
    public static final String TEXT_POWER = "Power";
    public static final String TEXT_MILEAGE = "Mileage";
    public static final String TAG_EQUIP = "equip";
    public static final String TAG_EQUIP_ID = "equip_id";
    public static final String TAG_EQUIP_NAME = "equip_name";
    public static final String TEXT_EQUIPMENT = "Equipment";
}
